### ISSUE TITLE
 The mod no longer works in 1.20.1

### ISSUE THREAD

**Issue by LucaLeukert** [ZsoltMolnarrr/TeamCapes#2]
Hello,

my friend and I were checking out mods on Modrinth and saw your mod. we tried it and i didn't. Some more support or a update would be nice.

**Comment by ZsoltMolnarrr** [comment]
It does work my friend :)

**Comment by LucaLeukert** [comment]
Maybe any advice on why it doesn't work??? Still unable to figure out how it works. Vanilla teams/team-colors don't create a banner.
