### ISSUE TITLE
I don't understand how it works((

### ISSUE THREAD

**Issue by Sivel0302** [ZsoltMolnarrr/TeamCapes#3]
I created 2 teams and joined one of them, but the cloaks are not displayed, I do not understand how the mod works at all

tell me how to turn everything on

**Comment by ZsoltMolnarrr** [comment]
Did you assign color to the teams?:)

**Comment by Sivel0302** [comment]
> Did you assign color to the teams?:)

How i can do this?

**Comment by Sivel0302** [comment]
> /team modify team_id color

this don't work((((
